name: "Build and Push Images"

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - ".github/workflows/build-push-image.yml"
    tags:
      - "*"

permissions:
  contents: read
  packages: write
  id-token: write
  security-events: write

jobs:
  build-images:
    name: "Build Images"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: "Generate images tags"
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            "ghcr.io/${{ github.repository_owner }}/conda-store-ui"
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: "Build docker images"
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          # Push to GHCR only on commit to `main`
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max